### ISSUE TITLE
Opening excel file using xlrd in HFSS python code

### ISSUE THREAD

**Issue by salahuddintariq** [linmingchih/HowtoSim_Script#1]
Hi, 

I am trying to open an excel file using xlrd in Python. How does that work? I have recorded a script from HFSS and it is running fine but I want to add a functionality in the code so that it may read a column from excel sheet and store it an array in Python and run the code. 
I will be grateful for your help.

**Comment by linmingchih** [comment]
Please view the latest video in HowtoSim
